In [ ]:
import pandas as pd

print(pd.__version__)

filename = "cleaned_census_tracts.csv"
df = pd.read_csv(filename)

3.0.5

In [2]:
df.head()

,OBJECTID,STATEFP,COUNTYFP,County,TRACTCE,GEOID,NAME,NAMELSAD,ALAND,AWATER,DAC,Income_Group,Urban_Rural_RuralCenter,PerCap_100k_L2DCFC,DAC_andor_LIC,UCC_eligible,REV2_eligible,Shape__Area,Shape__Length
0,3,6,37,Los Angeles County,204920,6037204920,2049.2,Census Tract 2049.20,909972,0,Disadvantaged Community,Low,Urban,0.000000,Yes,"Yes, eligible","No, ineligible",9.099752e+05,3900.202222
1,4,6,37,Los Angeles County,205110,6037205110,2051.1,Census Tract 2051.10,286960,0,Disadvantaged Community,Low,Urban,0.000000,Yes,"Yes, eligible","No, ineligible",2.869607e+05,2813.128130
2,5,6,37,Los Angeles County,205120,6037205120,2051.2,Census Tract 2051.20,1466130,0,Disadvantaged Community,Low,Urban,0.000000,Yes,"Yes, eligible","No, ineligible",1.466128e+06,6115.046898
3,6,6,37,Los Angeles County,206010,6037206010,2060.1,Census Tract 2060.10,1418138,20551,Disadvantaged Community,Low,Urban,363.989323,Yes,"No, ineligible","No, ineligible",1.438691e+06,6421.129173
4,8,6,37,Los Angeles County,206050,6037206050,2060.5,Census Tract 2060.50,1643426,94606,Disadvantaged Community,Low,Urban,0.000000,Yes,"Yes, eligible","No, ineligible",1.738033e+06,7759.974984

In [3]:
df.shape

(2310, 19)

In [4]:
df.columns

Index(['OBJECTID', 'STATEFP', 'COUNTYFP', 'County', 'TRACTCE', 'GEOID', 'NAME',
       'NAMELSAD', 'ALAND', 'AWATER', 'DAC', 'Income_Group',
       'Urban_Rural_RuralCenter', 'PerCap_100k_L2DCFC', 'DAC_andor_LIC',
       'UCC_eligible', 'REV2_eligible', 'Shape__Area', 'Shape__Length'],
      dtype='str')

In [5]:
df.dtypes

OBJECTID                     int64
STATEFP                      int64
COUNTYFP                     int64
County                         str
TRACTCE                      int64
GEOID                        int64
NAME                       float64
NAMELSAD                       str
ALAND                        int64
AWATER                       int64
DAC                            str
Income_Group                   str
Urban_Rural_RuralCenter        str
PerCap_100k_L2DCFC         float64
DAC_andor_LIC                  str
UCC_eligible                   str
REV2_eligible                  str
Shape__Area                float64
Shape__Length              float64
dtype: object

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2310 entries, 0 to 2309
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   OBJECTID                 2310 non-null   int64
 1   STATEFP                  2310 non-null   int64
 2   COUNTYFP                 2310 non-null   int64
 3   County                   2310 non-null   str
 4   TRACTCE                  2310 non-null   int64
 5   GEOID                    2310 non-null   int64
 6   NAME                     2310 non-null   float64
 7   NAMELSAD                 2310 non-null   str
 8   ALAND                    2310 non-null   int64
 9   AWATER                   2310 non-null   int64
 10  DAC                      2310 non-null   str
 11  Income_Group             2294 non-null   str
 12  Urban_Rural_RuralCenter  2310 non-null   str
 13  PerCap_100k_L2DCFC       2300 non-null   float64
 14  DAC_andor_LIC            2310 non-null   str
 15  UCC_eligible             2310 non-null   str
 16  REV2_eligible            2310 non-null   str
 17  Shape__Area              2310 non-null   float64
 18  Shape__Length            2310 non-null   float64
dtypes: float64(4), int64(7), str(8)
memory usage: 343.0 KB

In [8]:
mask = df["Income_Group"] == "Low"
df2 = df[mask]
df2

,OBJECTID,STATEFP,COUNTYFP,County,TRACTCE,GEOID,NAME,NAMELSAD,ALAND,AWATER,DAC,Income_Group,Urban_Rural_RuralCenter,PerCap_100k_L2DCFC,DAC_andor_LIC,UCC_eligible,REV2_eligible,Shape__Area,Shape__Length
0,3,6,37,Los Angeles County,204920,6037204920,2049.20,Census Tract 2049.20,909972,0,Disadvantaged Community,Low,Urban,0.000000,Yes,"Yes, eligible","No, ineligible",9.099752e+05,3900.202222
1,4,6,37,Los Angeles County,205110,6037205110,2051.10,Census Tract 2051.10,286960,0,Disadvantaged Community,Low,Urban,0.000000,Yes,"Yes, eligible","No, ineligible",2.869607e+05,2813.128130
2,5,6,37,Los Angeles County,205120,6037205120,2051.20,Census Tract 2051.20,1466130,0,Disadvantaged Community,Low,Urban,0.000000,Yes,"Yes, eligible","No, ineligible",1.466128e+06,6115.046898
3,6,6,37,Los Angeles County,206010,6037206010,2060.10,Census Tract 2060.10,1418138,20551,Disadvantaged Community,Low,Urban,363.989323,Yes,"No, ineligible","No, ineligible",1.438691e+06,6421.129173
4,8,6,37,Los Angeles County,206050,6037206050,2060.50,Census Tract 2060.50,1643426,94606,Disadvantaged Community,Low,Urban,0.000000,Yes,"Yes, eligible","No, ineligible",1.738033e+06,7759.974984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2305,8033,6,37,Los Angeles County,603302,6037603302,6033.02,Census Tract 6033.02,1124528,10554,Disadvantaged Community,Low,Urban,0.000000,Yes,"Yes, eligible","No, ineligible",1.135081e+06,4656.050244
2306,8034,6,37,Los Angeles County,603400,6037603400,6034.00,Census Tract 6034,1134323,0,Disadvantaged Community,Low,Urban,97.252614,Yes,"Yes, eligible","No, ineligible",1.134327e+06,4754.045156
2307,8035,6,37,Los Angeles County,603500,6037603500,6035.00,Census Tract 6035,794497,1096,Disadvantaged Community,Low,Urban,0.000000,Yes,"Yes, eligible","No, ineligible",7.955922e+05,3988.443160
2308,8037,6,85,Santa Clara County,512603,6085512603,5126.03,Census Tract 5126.03,2088703,0,Disadvantaged Community,Low,Urban,43.159258,Yes,"Yes, eligible","No, ineligible",2.088707e+06,7545.090576
2309,8041,6,37,Los Angeles County,603702,6037603702,6037.02,Census Tract 6037.02,2539340,73275,Disadvantaged Community,Low,Urban,0.000000,Yes,"Yes, eligible","No, ineligible",2.612616e+06,6679.682726