In [4]:
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
gas_plants = gpd.read_file("Manufactured_Gas_Plant_Sites.geojson")
counties = gpd.read_file("North_Carolina_State_and_County_Boundary_Polygons.geojson")
watersheds = gpd.read_file("dwq_wsws_20141126_-1629323221143849216.geojson")

Here I wanted to inspect and make sure the data was correctly imported

In [6]:
gas_plants.head()
gas_plants.shape

(32, 11)

In [7]:
counties.head()

,OBJECTID,County,FIPS,Rec_Survey,NCGS_url,ck_date,Shape__Area,Shape__Length,GlobalID,geometry
0,1,Alamance,001,Recorded survey data is available. Visit North...,https://ncem-gis.maps.arcgis.com/apps/webappvi...,2025-01-13 00:00:00+00:00,1.210717e+10,476733.362073,acd66e2b-e702-4b3a-82c1-eb86e12d3804,"POLYGON ((-79.25882 36.17252, -79.25959 36.133..."
1,2,Alexander,003,Recorded survey data is available. Visit North...,https://ncem-gis.maps.arcgis.com/apps/webappvi...,2025-01-13 00:00:00+00:00,7.343450e+09,387342.137292,6a1dac25-2574-4182-b77b-0074a5482dac,"POLYGON ((-81.10951 35.7766, -81.10973 35.7768..."
2,3,Alleghany,005,No recent survey data available,,2011-11-29 00:00:00+00:00,6.576362e+09,439166.717185,d8e726fa-ac7d-4212-a981-6ea0b111cee0,"POLYGON ((-81.25365 36.3666, -81.25325 36.3668..."
3,4,Anson,007,No recent survey data available,,2011-11-29 00:00:00+00:00,1.497020e+10,575503.754866,e4518706-732a-4abe-9079-9de6523b4747,"POLYGON ((-80.27683 35.19573, -80.27662 35.195..."
4,5,Ashe,009,Recorded survey data is available. Visit North...,https://ncem-gis.maps.arcgis.com/apps/webappvi...,2025-01-13 00:00:00+00:00,1.193926e+10,520084.244333,6d39c7ea-b7f4-4ac8-be47-65dfe4a46074,"POLYGON ((-81.47731 36.24026, -81.48632 36.241..."

In [8]:
watersheds.head()

,OBJECTID,class,STREAM_NAM,CL_DATE,PCA_TYPE,WSWS_PCA,ClassURL,Area_acers,SecClass,geometry
0,1,WS-IV,South Fork New River,7/3/2012,P,WS-IVP,http://deq.nc.gov/about/divisions/water-resour...,13347.827571,None,"POLYGON ((-81.56321 36.28102, -81.56375 36.280..."
1,2,WS-IV,South Fork New River,7/3/2012,C,WS-IVC,http://deq.nc.gov/about/divisions/water-resour...,187.988077,None,"POLYGON ((-81.56641 36.26867, -81.56677 36.268..."
2,3,WS-IV,Quarry,7/1/2012,C,WS-IVC,http://deq.nc.gov/about/divisions/water-resour...,18.593098,None,"POLYGON ((-78.15274 35.49434, -78.15273 35.494..."
3,4,WS-IV,Dan River,7/3/2012,P,WS-IVP,http://deq.nc.gov/about/divisions/water-resour...,22753.090916,None,"POLYGON ((-79.23098 36.53689, -79.23148 36.536..."
4,5,WS-IV,Haw River,3/1/2012,C,WS-IVC,http://deq.nc.gov/about/divisions/water-resour...,289.490421,None,"POLYGON ((-79.55208 36.2207, -79.55241 36.2215..."

Here I wanted to make sure all the files had the same projections, but since I want to calculate distance, they need to be converted

In [9]:
watersheds.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [10]:
watersheds.to_crs(epsg = 2264)

,OBJECTID,class,STREAM_NAM,CL_DATE,PCA_TYPE,WSWS_PCA,ClassURL,Area_acers,SecClass,geometry
0,1,WS-IV,South Fork New River,7/3/2012,P,WS-IVP,http://deq.nc.gov/about/divisions/water-resour...,13347.827571,None,"POLYGON ((1244528.994 930957.681, 1244368.181 ..."
1,2,WS-IV,South Fork New River,7/3/2012,C,WS-IVC,http://deq.nc.gov/about/divisions/water-resour...,187.988077,None,"POLYGON ((1243471.002 926487.335, 1243366.679 ..."
2,3,WS-IV,Quarry,7/1/2012,C,WS-IVC,http://deq.nc.gov/about/divisions/water-resour...,18.593098,None,"POLYGON ((2252186.174 635920.159, 2252188.762 ..."
3,4,WS-IV,Dan River,7/3/2012,P,WS-IVP,http://deq.nc.gov/about/divisions/water-resour...,22753.090916,None,"POLYGON ((1932129.921 1014442.458, 1931983.152..."
4,5,WS-IV,Haw River,3/1/2012,C,WS-IVC,http://deq.nc.gov/about/divisions/water-resour...,289.490421,None,"POLYGON ((1837143.609 899694.5, 1837047.637 90..."
...,...,...,...,...,...,...,...,...,...,...
442,443,WS-IV,Roanoke River,1/1/2013,C,WS-IVC,http://deq.nc.gov/about/divisions/water-resour...,313.414342,None,"POLYGON ((2581129.158 776393.158, 2581161.662 ..."
443,444,WS-IV,Green River Lake Adger,9/1/2014,P,WS-IVP,http://deq.nc.gov/about/divisions/water-resour...,17421.746816,None,"POLYGON ((1045405.467 599269.465, 1045344.902 ..."
444,445,WS-IV,Green River Lake Adger,9/1/2014,C,WS-IVC,http://deq.nc.gov/about/divisions/water-resour...,3153.742849,None,"POLYGON ((1045405.467 599269.465, 1045427.816 ..."
445,446,WS-IV,Lake James,,C,WS-IVC,http://deq.nc.gov/about/divisions/water-resour...,NaN,None,"POLYGON ((1110702.223 731707.045, 1110707.875 ..."
446,447,WS-IV,Lake James,,P,WS-IVP,http://deq.nc.gov/about/divisions/water-resour...,NaN,None,"MULTIPOLYGON (((1153051.055 732545.061, 115292..."

In [11]:
gas_plants.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [12]:
gas_plants.to_crs(epsg = 2264)

,objectid,epaid,sitename,cerclis_n,siteaddr,sitecity,sitecounty,yrs_op,lead_rp,status,geometry
0,1,NONCD0000032,Asheville MGP 2,Asheville Coal Gas Plant No 2,173 S Charotte Street,Asheville,Buncombe,1893-1907,Progress Energy,A,POINT (944764.987 688680.285)
1,2,NCD986188787,Asheville MGP 1,Asheville Coal Gas Plant No 1,31 Riverside Drive,Asheville,Buncombe,1902-1953,Progress Energy,A,POINT (939584.74 687008.98)
2,3,NONCD0000002,Burlington MGP,Burlington Coal Gas Plant,1205 North Church Street,Burlington,Alamance,1925-1953,Duke Power,A,POINT (1876377.746 854446.146)
3,4,,Charlotte MGP No 1,Charlotte Coal Gas Plant No 1,200 South College Street,Charlotte,Mecklenburg,1857-1900,unkown,I,POINT (1449354.148 542075.524)
4,5,NCD986188803,Charlotte MGP No 2,Charlotte Coal Gas Plant No 2,1400 South Boulevard,Charlotte,Mecklenburg,1899-1955,Duke Power,A,POINT (1446287.37 538615.609)
5,6,NCD986197333,Concord MGP,Concord Coal Gas Plant,183 Academy Avenue,Concord,Cabarrus,1911-1950,SCANA/PSNC,A,POINT (1525652.898 608556.336)
6,7,NCD986173938,Durham MGP,Durham Gas Plant,708 Gilbert Street,Durham,Durham,1910-1955,SCANA/PSNC,A,POINT (2033002.421 817615.185)
7,8,NCD986197267,Elizabeth City MGP,Elizabeth City Coal Gas,Ward Street,Elizabeth City,Pasquotank,1898-1958,AGL Resources,A,POINT (2819831.226 942975.923)
8,9,NCD986197341,Fayetteville MGP,Fayetteville Coal Gas/Ray Ave,Ray Avenue,Fayetteville,Cumberland,1859-1948,City of Fayetteville,A,POINT (2035273.839 475679.685)
9,10,NCD986188829,Gastonia MGP,Gastonia Coal Gas Plant,Caldwell Street,Gastonia,Gaston,1920-1950,SCANA/PSNC,I,POINT (1348222.217 562646.754)
10,11,NCD986197309,Goldsboro MGP No 1,Goldsboro Coal Gas Plant No 1,Virginia and Vine Streets,Goldsboro,Wayne,1900-1940,unknown,I,POINT (2298152.183 598884.445)
11,12,NCD981861743,Greensboro MGP No 2,Duke Power/Greensboro Gas Plant,Friendly Ave and Church Street,Greensboro,Guilford,1910-1955,Duke Power,A,POINT (1767823.824 846773.398)
12,13,NONCD0001089,Greensboro MGP No 1,Greensboro Coal Gas Plant No 1,Church Street,Greensboro,Guilford,NA,Duke Power,A,POINT (1767588.513 846355.154)
13,14,NCD986188886,Greenville MGP,Greenville Coal Gas Plant,Plant Street,Greenville,Pitt,1926-1951,Greenville Utilities Commission,A,POINT (2482335.916 683102.576)
14,15,NONCD0001084,Henderson MGP,Henderson Coal Gas Plant,Yadkin Street,Henderson,Vance,1912-1942,unknown,I,POINT (2169725.772 939403.122)
15,16,NONCD0001085,Hickory MGP,Hickory Coal Gas Plant,625 12th Street Drive NW,Hickory,Catawba,1933-1948,PNG,I,POINT (1298170.339 733455.117)
16,17,NCD986188837,High Point MGP,High Point Coal Gas Plant,Centennial St and Kivett Drive,High Point,Guilford,1912-1948,Duke Power,I,POINT (1703832.618 805852.295)
17,18,NCD986197366,Kinston MGP,Kinston Coal Gas Plant,South St and Herritage Street,Kinston,Lenoir,1925-1952,Progress Energy,A,POINT (2422394.869 550998.135)
18,19,NCD986197358,Lexington MGP,Lexington Coal Gas Plant,Gas Plant Road or SR 2001,Lexington,Davidson,1920-1950,unknown,I,POINT (1637231.691 759588.715)
19,20,NCD986197259,New Bern MGP,New Bern Coal Gas Plant,506 Tryon Palace Drive,New Bern,Craven,1859-1947,Progress Energy,A,POINT (2585374.932 499078.885)
20,21,NCD986188894,Raleigh MGP No 1,Raleigh Coal Gas Plant No 1,McDowell St and Cararrus Street,Raleigh,Wake,1872-1914,Progress Energy,A,POINT (2105917.923 736795.183)
21,22,NCD986188902,Raleigh MGP No 2,Raleigh Coal Gas Plant No 2,600 West Cabarrus Street,Raleigh,Wake,1916-1953,SCANA/PSNC,A,POINT (2104522.548 737303.794)
22,23,NONCD0001087,Reidsville MGP,Reidsville Coal Gas Plant,825 Way Street,Reidsville,Rockingham,1929-1946,PNG,I,POINT (1805553.373 946552.215)
23,24,NCD986197325,Rocky Mount MGP No 1,Rocky Mount Coal Gas Plant No 1,Wye Street,Rocky Mount,Edgecomb,1905-1936,unknown,I,POINT (2355422.845 796019.983)
24,25,NCD986197317,Rocky Mount MGP No 2,Rocky Mount Coal Gas Plant No 2,100 East Virginia Street,Rocky Mount,Edgecomb,1920-1950,City of Rocky Mount,I,POINT (2357855.403 803262.257)
25,26,NCD986197283,Salisbury MGP No 1,Salisbury Coal Gas Plant No 1,324 East Liberty Street,Salisbury,Rowan,1910-1948,Duke Power,A,POINT (1564957.802 700973.96)
26,27,NCD986197291,Statesville MGP,Statesville Coal Gas Plant,615 South Center Street,Statesville,Iredell,1918-1945,SCANA/PSNC,I,POINT (1441129.789 743451.492)
27,28,NCD986197275,Washington MGP,Washington Coal Gas Plant,West 3rd Street,Washington,Beaufort,1857-1947,Progress Energy,A,POINT (2576149.998 659942.401)
28,29,NCD986188910,Wilmington MGP,Wilminton Coal Gas Plant,Castle St and Surry Street,Wilmington,New Hanover,1883-1952,Progress Energy,A,POINT (2317508.167 175358.169)
29,30,NCD986166700,Wilson MGP,Toisnot Swamp,Pine Street,Wilson,Wilson,1916-1946,City of Wilson,A,POINT (2325796.038 724112.64)
30,31,NCD986188845,Winston-Salem MGP No 1,Winston-Salem Coal Gas Plant No 1,501 East Third Street,Winston-Salem,Forsyth,1900-1958,Duke Power,A,POINT (1633920.235 857127.88)
31,32,NCD986188852,Winston-Salem MGP No 2,Winston-Salem Coal Gas Plant No 2,Brookstown Avenue,Winston-Salem,Forsyth,1858-1900,unknown,I,POINT (1632258.52 854414.539)

In [13]:
counties.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [14]:
counties.to_crs(epsg= 2264)

,OBJECTID,County,FIPS,Rec_Survey,NCGS_url,ck_date,Shape__Area,Shape__Length,GlobalID,geometry
0,1,Alamance,001,Recorded survey data is available. Visit North...,https://ncem-gis.maps.arcgis.com/apps/webappvi...,2025-01-13 00:00:00+00:00,1.210717e+10,476733.362073,acd66e2b-e702-4b3a-82c1-eb86e12d3804,"POLYGON ((1923604.345 881802.091, 1923341.195 ..."
1,2,Alexander,003,Recorded survey data is available. Visit North...,https://ncem-gis.maps.arcgis.com/apps/webappvi...,2025-01-13 00:00:00+00:00,7.343450e+09,387342.137292,6a1dac25-2574-4182-b77b-0074a5482dac,"POLYGON ((1374326.862 744227.342, 1374262.766 ..."
2,3,Alleghany,005,No recent survey data available,,2011-11-29 00:00:00+00:00,6.576362e+09,439166.717185,d8e726fa-ac7d-4212-a981-6ea0b111cee0,"POLYGON ((1336457.551 959892.73, 1336578.943 9..."
3,4,Anson,007,No recent survey data available,,2011-11-29 00:00:00+00:00,1.497020e+10,575503.754866,e4518706-732a-4abe-9079-9de6523b4747,"POLYGON ((1618558.995 528615.286, 1618623 5286..."
4,5,Ashe,009,Recorded survey data is available. Visit North...,https://ncem-gis.maps.arcgis.com/apps/webappvi...,2025-01-13 00:00:00+00:00,1.193926e+10,520084.244333,6d39c7ea-b7f4-4ac8-be47-65dfe4a46074,"POLYGON ((1269470.886 915478.909, 1266824.855 ..."
...,...,...,...,...,...,...,...,...,...,...
95,96,Wayne,191,Recorded survey data is available. Visit North...,https://ncem-gis.maps.arcgis.com/apps/webappvi...,2025-01-13 00:00:00+00:00,1.554411e+10,579779.305793,d8af9501-60d9-48eb-95b0-fe5d25bfa0c2,"POLYGON ((2297704.655 669585.811, 2297802.27 6..."
96,97,Wilkes,193,Recorded survey data is available. Visit North...,https://ncem-gis.maps.arcgis.com/apps/webappvi...,2025-01-13 00:00:00+00:00,2.111152e+10,718180.039408,69241b1a-84e3-4fa4-8b2e-197d151c8dbe,"POLYGON ((1319003.919 828582.081, 1318920.299 ..."
97,98,Wilson,195,Recorded survey data is available. Visit North...,https://ncem-gis.maps.arcgis.com/apps/webappvi...,2025-01-13 00:00:00+00:00,1.039961e+10,430628.770432,2b485dcd-086d-441f-9e9c-c33b82b18800,"POLYGON ((2350081.935 670058.039, 2349948.507 ..."
98,99,Yadkin,197,Recorded survey data is available. Visit North...,https://ncem-gis.maps.arcgis.com/apps/webappvi...,2025-01-13 00:00:00+00:00,9.415514e+09,452687.390790,1434800b-c873-4475-8865-cea54663d8f2,"POLYGON ((1557884.733 838963.611, 1557598.265 ..."
99,100,Yancey,199,Recorded survey data is available. Visit North...,https://ncem-gis.maps.arcgis.com/apps/webappvi...,2025-01-13 00:00:00+00:00,8.729856e+09,540459.653576,279eb86b-4918-4bf9-956c-72a4919205d7,"POLYGON ((1071316.169 769243.913, 1071210.783 ..."

Here I want to find how many gas plants are within watersheds

In [15]:
plants_in_watersheds = gpd.sjoin(gas_plants, watersheds, predicate= "within")
len(plants_in_watersheds)
plants_in_watersheds

,objectid,epaid,sitename,cerclis_n,siteaddr,sitecity,sitecounty,yrs_op,lead_rp,status,...,index_right,OBJECTID,class,STREAM_NAM,CL_DATE,PCA_TYPE,WSWS_PCA,ClassURL,Area_acers,SecClass
15,16,NONCD0001085,Hickory MGP,Hickory Coal Gas Plant,625 12th Street Drive NW,Hickory,Catawba,1933-1948,PNG,I,...,316,317,WS-IV,Lake Hickory,8/3/92,P,WS-IVP,http://deq.nc.gov/about/divisions/water-resour...,15332.201671,None
16,17,NCD986188837,High Point MGP,High Point Coal Gas Plant,Centennial St and Kivett Drive,High Point,Guilford,1912-1948,Duke Power,I,...,281,282,WS-IV,Deep River (Randleman Lake),9/1/74,P,WS-IVP,http://deq.nc.gov/about/divisions/water-resour...,25022.565530,None

I've realized that my gas plant dataset already contains county information, so my counties dataset isn't necessary. I asked ChatGPT what data I could add to make my analysis more robust and fulfill the assignment requirements, and it recommended analyzing water quality assessment information, so I have downloaded bethos sample results to hopefully test whether these gas plants are affecting waterways

In [16]:
benthos = gpd.read_file("NC_DWR_Benthos_Sample_Results.geojson")

In [17]:
benthos.head()

,Site_ID,View_Details,Water_Body,Location,County,Sampled_Rating,Longitude,Latitude,Latest_Rating,Study_Type,ObjectId,geometry
0,BB290,"<a href=""http://www.ncwater.org/?page=672&Site...",AVENTS CR,SR 1418,Harnett,<br />28 May 2013 / Excellent<br />23 Apr 2007...,-78.910000,35.487222,Excellent,Special Study,1,POINT (-78.90969 35.48798)
1,BB285,"<a href=""http://www.ncwater.org/?page=672&Site...",AVENTS CR,SR 1403,Harnett,<br />19 Sep 2000 / Good,-78.899444,35.506389,Good,Special Study,2,POINT (-78.89894 35.50662)
2,BB286,"<a href=""http://www.ncwater.org/?page=672&Site...",JUMP AND RUN CR,BE NC 133,Brunswick,<br />17 May 1995 / Not Rated,-78.052222,33.947778,Not Rated,N/A,3,POINT (-78.05222 33.94778)
3,BB287,"<a href=""http://www.ncwater.org/?page=672&Site...",PARKERS CR,SR 1407,Harnett,<br />14 Mar 2003 / Not Impaired,-78.894722,35.547500,Not Impaired,Special Study,4,POINT (-78.89457 35.54767)
4,BB288,"<a href=""http://www.ncwater.org/?page=672&Site...",LEWIS SWP,SR 1410,Brunswick,<br />25 Feb 2003 / Natural<br />04 Mar 1998 /...,-78.170000,34.162500,Natural,Basin Sample,5,POINT (-78.16959 34.16307)

In [18]:
benthos.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [20]:
benthos.to_crs(epsg=2264)

,Site_ID,View_Details,Water_Body,Location,County,Sampled_Rating,Longitude,Latitude,Latest_Rating,Study_Type,ObjectId,geometry
0,BB290,"<a href=""http://www.ncwater.org/?page=672&Site...",AVENTS CR,SR 1418,Harnett,<br />28 May 2013 / Excellent<br />23 Apr 2007...,-78.910000,35.487222,Excellent,Special Study,1,POINT (2026882.318 632539.135)
1,BB285,"<a href=""http://www.ncwater.org/?page=672&Site...",AVENTS CR,SR 1403,Harnett,<br />19 Sep 2000 / Good,-78.899444,35.506389,Good,Special Study,2,POINT (2030076.901 639328.775)
2,BB286,"<a href=""http://www.ncwater.org/?page=672&Site...",JUMP AND RUN CR,BE NC 133,Brunswick,<br />17 May 1995 / Not Rated,-78.052222,33.947778,Not Rated,N/A,3,POINT (2287479.045 73357.756)
3,BB287,"<a href=""http://www.ncwater.org/?page=672&Site...",PARKERS CR,SR 1407,Harnett,<br />14 Mar 2003 / Not Impaired,-78.894722,35.547500,Not Impaired,Special Study,4,POINT (2031361.985 654267.901)
4,BB288,"<a href=""http://www.ncwater.org/?page=672&Site...",LEWIS SWP,SR 1410,Brunswick,<br />25 Feb 2003 / Natural<br />04 Mar 1998 /...,-78.170000,34.162500,Natural,Basin Sample,5,POINT (2251224.114 151391.337)
...,...,...,...,...,...,...,...,...,...,...,...,...
3432,JB349,"<a href=""http://www.ncwater.org/?page=672&Site...",E PR ENO R,BE SR 1323,Orange,<br />10 Jul 2014 / Fair,-79.152470,36.145680,Fair,Special Study,3581,POINT (1954980.916 871965.311)
3433,JB350,"<a href=""http://www.ncwater.org/?page=672&Site...",E PR ENO R,SR 1332,Orange,<br />10 Jul 2014 / Good-Fair,-79.157730,36.137430,Good-Fair,Special Study,3582,POINT (1953423.05 868964.377)
3434,JB352,"<a href=""http://www.ncwater.org/?page=672&Site...",LITTLE CR,US 264 ALT,Nash,<br />25 Apr 2019 / Fair,-78.236200,35.809630,Fair,Special Study,3583,POINT (2226462.627 750473.058)
3435,JB353,"<a href=""http://www.ncwater.org/?page=672&Site...",UT FLAT R,SR 1626,Durham,<br />01 Apr 2021 / Excellent,-78.841340,36.134700,Excellent,Special Study,3584,POINT (2046853.163 867970.978)
3436,JB363,"<a href=""http://www.ncwater.org/?page=672&Site...",JUMPING RUN CR,"SITE 1, OFF SR 1613",Alexander,<br />28 Oct 2013 / Not Rated,-81.137066,35.890630,Not Rated,Special Study,3585,POINT (1367048.696 785899.306)

I used ChatGPT to figure out how to create a new filtered dataset

In [35]:
bad_benthos = benthos[benthos["Latest_Rating"].isin(["Poor", "Severe"])]

In [36]:
bad_benthos

,Site_ID,View_Details,Water_Body,Location,County,Sampled_Rating,Longitude,Latitude,Latest_Rating,Study_Type,ObjectId,geometry
6,BB291,"<a href=""http://www.ncwater.org/?page=672&Site...",L BUFFALO CR,SR 1420,Lee,<br />05 Mar 2003 / Poor<br />25 Feb 1993 / Poor,-79.174722,35.531667,Poor,Basin Sample,8,POINT (-79.17355 35.53169)
11,CB195,"<a href=""http://www.ncwater.org/?page=672&Site...",MAUNEY CR,SR 1831,Gaston,<br />04 May 2006 / Poor<br />13 May 1997 / Fair,-81.118333,35.356944,Poor,Special Study,13,POINT (-81.11802 35.35741)
43,BB014,"<a href=""http://www.ncwater.org/?page=672&Site...",L TROUBLESOME CR,SR 2598,Rockingham,<br />02 May 1985 / Poor,-79.641389,36.294722,Poor,N/A,46,POINT (-79.64139 36.29472)
54,BB025,"<a href=""http://www.ncwater.org/?page=672&Site...",MILE RUN CR,SR 1400,Guilford,<br />28 Apr 1986 / Poor,-79.774444,36.043333,Poor,N/A,57,POINT (-79.77444 36.04333)
55,BB026,"<a href=""http://www.ncwater.org/?page=672&Site...",N BUFFALO CR,NR FAIRVIEW ST,Guilford,<br />29 Jul 1997 / Poor<br />09 Nov 1988 / Poor,-79.770833,36.102778,Poor,N/A,59,POINT (-79.77083 36.10278)
...,...,...,...,...,...,...,...,...,...,...,...,...
3413,QB050,"<a href=""http://www.ncwater.org/?page=672&Site...",LONG CR,NC 268,Wilkes,<br />12 Sep 1990 / Poor,-81.141667,36.179722,Poor,Special Study,3562,POINT (-81.14167 36.17972)
3414,JB339,"<a href=""http://www.ncwater.org/?page=672&Site...",WILLIAMS CR,BE PINE LAKE DAM,Wake,<br />01 May 2014 / Poor,-78.817400,35.746633,Poor,Special Study,3563,POINT (-78.8174 35.74663)
3416,JB340,"<a href=""http://www.ncwater.org/?page=672&Site...",WILLIAMS CR,BE LAKE PINE DR,Wake,<br />01 May 2014 / Poor,-78.815516,35.745850,Poor,Special Study,3565,POINT (-78.81552 35.74585)
3417,JB341,"<a href=""http://www.ncwater.org/?page=672&Site...",SWIFT CR,OFF GREGSON RD,Wake,<br />06 May 2014 / Poor,-78.804650,35.738500,Poor,Special Study,3566,POINT (-78.80465 35.7385)
3420,OB161,"<a href=""http://www.ncwater.org/?page=672&Site...",TOWN CR,SR1400,Wilson,<br />07 Feb 2007 / Severe,-77.840000,35.821389,Severe,Special Study,3569,POINT (-77.84 35.82139)

In [37]:
df = gpd.sjoin(bad_benthos, plants_in_watersheds, predicate= "intersects")

ValueError: 'index_right' cannot be a column name in the frames being joined

I asked ChatGPT why I got an error in the code above "'index_right' cannot be a column name in the frames being joined"

In [38]:
plants_in_watersheds = plants_in_watersheds.drop(columns="index_right")

In [41]:
df = gpd.sjoin(bad_benthos, plants_in_watersheds, predicate= "touches")

In [42]:
df

Empty GeoDataFrame
Columns: [Site_ID, View_Details, Water_Body, Location, County, Sampled_Rating, Longitude, Latitude, Latest_Rating, Study_Type, ObjectId, geometry, index_right, objectid, epaid, sitename, cerclis_n, siteaddr, sitecity, sitecounty, yrs_op, lead_rp, status, OBJECTID, class, STREAM_NAM, CL_DATE, PCA_TYPE, WSWS_PCA, ClassURL, Area_acers, SecClass]
Index: []

[0 rows x 32 columns]

Should I create a buffer aroud the benthos assessments?